cursor #dee2ef
cursor_text_color #bdc7dc

foreground            #dee2ef
background            #0f141c
selection_foreground  #00363d
selection_background  #82d3e2
url_color             #50d8ed

color0   #0f141c
color1   #ff4585
color2   #50ed5e
color3   #fff245
color4   #2ec9e1
color5   #005f6d
color6   #50d8ed
color7   #e5f6f8
color8   #8a989a
color9   #ff80ab
color10  #88ff94
color11  #fff688
color12  #6febff
color13  #88efff
color14  #b2f4ff
color15  #f6fdff
