font_family JetBrainsMono Nerd Font
font_size 12

enable_audio_bell no

confirm_os_window_close 0

shell_integration enabled
include cyberdream.conf
background_opacity 0.6
background_blur 32
shell tmux new-session
hide_window_decorations yes
